version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8888 # Environment variable for frontend API

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mern_app # MongoDB 
      DATABASE: mongodb://mongo:27017/mern_app

    volumes:
      - ./backend:/app # Optional for live development

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
